---
- name: Boot baremetal to desired state
  hosts: localhost
  vars_files:
    - vars/vars.yml

  vars:
    state: present

  roles:
    - 010-flavor
    - 011-flavor-capabilities
    - 012-port
    - 012-port-facts
    - 013-instance
    - 014-check-state
    - 015-inventory

- name: Execute prereqs
  hosts: openstack
  become: true
  vars_files:
   - vars/vars.yml

  roles:
    - { role: 021-rhel-pre, when ansible_os_family == 'RedHat' }
    - 025-phoronix-pre


- name: Execute test
  hosts: openstack
  become_user: cloud-user
  vars_files:
   - vars/vars.yml

  roles:
    - 030-phoronix
