---
- name: Gather facts about port
  hosts: localhost

  vars_files:
   - vars/vars.yml

  roles:
    - 012-port-facts
    - 015-inventory


- name: Execute pre-reqs
  hosts: openstack
  become: true
  vars_files:
   - vars/vars.yml

  roles:
    - 021-rhel-pre
    - 025-phoronix-pre
    - 021-rhel-pre


- name: Execute test
  hosts: openstack
  become_user: "{{ cloud_user }}"
  vars_files:
   - vars/vars.yml

  roles:
    - 030-phoronix
