---
#- name: Gathering facts on vm-instance
#  os_server_facts:
#    auth:
#       auth_url: "{{ os_auth }}"
#       username: "{{ project_name }}"
#       password: "{{ project_password }}"
#       project_name: "{{ project_name }}"
#    server: "VM-Instance-{{ test_name }}"
#    validate_certs: False
#  register: vm_instance_deployed

- name: Display variable openstack port
  debug:
    var: vm_port


- name: add undercloud to ansible inventory
  add_host:
     name: "vm_instance-{{ item.item }}"
     groups: openstack
     ansible_host: "{{ item.ansible_facts.openstack_ports.0.fixed_ips.0.ip_address }}"
     ansible_user: "{{ cloud_user }}"
     ansible_become: true
  with_items: "{{ vm_port.results }}"
