---
  - name: Re-learn VM network port
    os_port_facts:
       auth:
         auth_url: "{{ os_auth }}"
         username: "{{ project_name }}"
         password: "{{ project_password }}"
         project_name: "{{ project_name }}"
       port: "VMport{{ item }}-{{ memory }}{{ cpu }}{{ system }}-{{ test_name }}" 
       validate_certs: False
    register: vm_port
    with_sequence: count={{ vm_count }}


  - debug:
       var: vm_port
