---
  - name: Ensure flavor for baremetal discovery is "{{ state }}"
    os_nova_flavor:
       auth:
         auth_url: "{{ os_auth }}"
         username: "{{ admin_name }}"
         password: "{{ admin_password }}"
         project_name: "{{ admin_name }}"
       state: "{{ state }}"
       name: "discovery-{{ item }}"
       ram: 1024
       vcpus: 1
       disk: 10
       validate_certs: False
       extra_specs: 
         "baremetal": "true"
         "capabilities:ironic_uuid": "{{ item }}"
    with_items: "{{ ironic_nodes.stdout_lines }}"

