---

- name: verify baremetal is up and reachable
  command: >
    ssh -o BatchMode=yes -o StrictHostKeyChecking=no
    {{cloud_user}}@{{bm_port.ansible_facts.openstack_ports.0.fixed_ips.0.ip_address}} true
  register: result
  until: result|success
  retries: 30
  delay: 20

